import { subjects, allChapters, quizzes } from "../app/subjects/data";

export { subjects, allChapters as chapters, quizzes };

export const students = [
  {
    id: "1",
    name: "Ahmad Fauzi",
    email: "ahmad.fauzi@example.com",
    school: "SMA Negeri 1 Jakarta",
    targetUniversity: "Universitas Indonesia",
    progress: 75,
    xp: 2500,
    level: 12,
    streak: 15,
  },
  {
    id: "2",
    name: "Siti Aminah",
    email: "siti.aminah@example.com",
    school: "SMA Negeri 8 Jakarta",
    targetUniversity: "Institut Teknologi Bandung",
    progress: 60,
    xp: 1850,
    level: 9,
    streak: 8,
  },
  {
    id: "3",
    name: "Budi Santoso",
    email: "budi.santoso@example.com",
    school: "SMA Negeri 3 Bandung",
    targetUniversity: "Universitas Gadjah Mada",
    progress: 90,
    xp: 3200,
    level: 15,
    streak: 22,
  },
  {
    id: "4",
    name: "Dewi Lestari",
    email: "dewi.lestari@example.com",
    school: "SMA IC Al-Kausar",
    targetUniversity: "Universitas Indonesia",
    progress: 45,
    xp: 1200,
    level: 6,
    streak: 4,
  },
  {
    id: "5",
    name: "Rizky Pratama",
    email: "rizky.pratama@example.com",
    school: "SMA Negeri 1 Yogyakarta",
    targetUniversity: "Universitas Gadjah Mada",
    progress: 65,
    xp: 2100,
    level: 10,
    streak: 12,
  },
  {
    id: "6",
    name: "Lani Wijaya",
    email: "lani.wijaya@example.com",
    school: "SMA Taruna Nusantara",
    targetUniversity: "Institut Teknologi Sepuluh Nopember",
    progress: 30,
    xp: 950,
    level: 5,
    streak: 3,
  },
];
export const settings = {
  examDate: "2026-05-15",
  targetThreshold: 80,
};
